services:
  mysql:
    image: mysql:8.0
    container_name: supportflow-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: supportflow_db
      MYSQL_USER: supportflow
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - supportflow_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: supportflow-api
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=supportflow_db;User=supportflow;Password=${MYSQL_PASSWORD};"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: SupportFlow
      Jwt__Audience: SupportFlowUsers

    ports:
      - "8080:8080"

volumes:
  supportflow_mysql_data: